### ISSUE TITLE
Possible change of the props id in the accessories.

### ISSUE THREAD

**Issue by heyner29** [enso-ui/accessories#3]
This is  a **feature request**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description

Good morning, I'm already starting to migrate my app from version Enso 2 to Enso 3. That aproposito I'm grateful for such an excellent job. Do you think it is possible for the props to be changed so that they also admit string as id?. Ps in some models use UUID :(
In the previous version, I overwrote the [line](https://github.com/enso-ui/accessories/blob/3f01d9bbef0e5e0c35ed1fdad387aaa166a341ba/src/bulma/addresses/Addresses.vue#L86) with a matrix `type: [String, Number]` in the resources and I read that in this it is possible with the patch-package, only that it occurred to me that they can be used like this in a generic way. I am not sure if this affects the performance and that is why it is not used, or on the contrary it has not been used because it has not been required. Obviously what I suggest I suggest for all the accessories if possible (Addresses, comments, discussions, documents).

Thank you

**Comment by aocneanu** [comment]
Make a PR with this change on all the 4 components and I'll merge it

**Comment by aocneanu** [comment]
@heyner29 Do you consider doing this?

**Comment by heyner29** [comment]
@aocneanu Hello, if you excuse me but I've been a bit busy with other things. But in what runs this week I'll do PR

**Comment by aocneanu** [comment]
merged
